### ISSUE TITLE
Analyze the ZoomStack package (as a potential testbed for multi-resolution optimizations)

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/testbed16#11]
ZoomStack is a free multiresolution stack that covers the entire UK, released by ordnance survey.

We now have a GeoServer data directory which we can use for the outdoor style. There are other styles which we can configure.

**Comment by simboss** [comment]
@aaime is this something we can share with the public like we did for the OSM styles and data directory?

**Comment by aaime** [comment]
We have two datasets:

* The [OS Topography](https://www.ordnancesurvey.co.uk/business-government/products/mastermap-topography) map, a licensed, high resolution only, massive dataset (between 200 and 300GB depending on the size). We cannot redistribute it (give the size, we don't want to) but the [styles are open ](https://github.com/OrdnanceSurvey/OSMM-Topography-Layer-stylesheets/tree/master/Schema%20version%209/Stylesheets/Geoserver%20stylesheets%20(SLD)). There are multiple styling options.

* The [OS Zoomstack](https://www.ordnancesurvey.co.uk/business-government/products/open-zoomstack) map, a multi-resolution free map that's still like 12GB. The [styles for this one](https://github.com/OrdnanceSurvey/OS-Open-Zoomstack-Stylesheets/tree/master/Vector%20Tiles/Mapbox%20GL%20Styles) are free as well, again with multiple styling options.

We would setup a data directory with the styles, layers and groups ready to use, and people would just have to download and setup the data. For zoomstack it's a geopackage download, for topography they provide GMLs that are then to be imported into PostGIS with a tool (Lutra's Consulting Translator 2).
