### ISSUE TITLE
Set up continous deploy on jenkins

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/testbed16#14]
Use an existing job for maps or vtp as a reference.

TODO:
- [ ] Setup a build job to create a docker image from the GeoServer master (see [vtp2 geoserver job](https://build.geo-solutions.it/jenkins/view/vtp2%20geoserver/job/vtp2%20geoserver/) for reference)
  - The GeoServer instance must include the following plugins:
    - [ ] WPS (wps-plugin)
    - [ ] GeoPackage (geopkg-plugin)
- [ ] Trigger a deploy on the server when a new image is available (see [vtp2 geoserver deployment](https://build.geo-solutions.it/jenkins/view/vtp2%20geoserver/job/vtp2%20geoserver%20deployment/) job for reference)
- [ ] Update the [deploy document](https://docs.google.com/document/d/1faQPr3F1Ey3-Vm9qJ6O1IDvl15nq0bPyEDhms6P3-FY/edit#heading=h.ak5750ty005j) with instructions on how to manage the deploy pipeline (start/stop)

**Comment by randomorder** [comment]
I drafted the build and the deploy jobs [here](https://build.geo-solutions.it/jenkins/view/TestBed16/)
Currently the deployment job is not using Ansible though so I'd like to update it to use ansible instead. What do you think @paltaa? How long would it take to implement it?

**Comment by paltaa** [comment]
working on this, will update soon

**Comment by paltaa** [comment]
im stuck waiting for either get access to install the ansible plugin in jenkins or wait until someone installs it

**Comment by randomorder** [comment]
Hi Juan

Ansible installed
```
ansible --version
/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a release (2.7.7+) that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,
ansible 2.9.9
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]
root@build:/home/geosolutions# which ansible
/usr/local/bin/ansible
```

Ansible Plugin installed in Jenkins too.

let me know if you need anything else

**Comment by paltaa** [comment]
Okay, job working for deployment, going to setup trigger

**Comment by randomorder** [comment]
Trigger is not required. The deployment job is  triggered automatically by the docker image building job.

@aaime you can start using the server. Let us know if you need anything else (extensions, utils on the machine, ...)
