### ISSUE TITLE
Add TLS certificate

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/testbed16#15]
TLS must be enabled.
TODO:

- [ ] Buy a certificate (@randomorder please confirm we won't reuse a star certificate for this server)
- [ ] Edit ansible playbooks to include the **encrypted** certificate
- [ ] Update documentation and credentials document
- [ ] Deploy

**Comment by randomorder** [comment]
> TLS must be enabled.
> TODO:
> 
> * [ ]  Buy a certificate (@randomorder please confirm we won't reuse a star certificate for this server)

We'll reuse the wildcard cert we have. For the moment you can use a self-signed certificate @paltaa
