### ISSUE TITLE
GeoServer Datadir not Bound Properly

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/testbed16#16]
It looks like after every deploy the GeoServer data directory is cleared after Every deploy. This setup is dockerized so I suspect that the volume or directory is not bound properly.

This means we loose the configuration every time. Fix it ASAP

For the moment I have stopped the Jenkins CD job so that @aaime can work on GeoServer.
Remember to take a backup before working on it. We don't want to loose Andrea's work

**Comment by randomorder** [comment]
What is the purpose of [this](https://github.com/geosolutions-it/testbed16/blob/master/stack/bring_up_geoserver.yml#L67) last step? it looks like the override file is ignored

**Comment by randomorder** [comment]
@paltaa
Please check my feedback above
I created a tentative patch (PR [here](https://github.com/geosolutions-it/testbed16/pull/17)) and updated the [jenkins job](https://build.geo-solutions.it/jenkins/job/TestBed16%20GeoServer%20Deployment/configure) to build from the branch instead master.

Please review and let me know. If you merge the PR remember to update the jenkins job accordingly

**Comment by paltaa** [comment]
Yes, the missing override.yml made datadir not mount correctly, merging pr

**Comment by paltaa** [comment]
Updated branch in Jenkins job
