### ISSUE TITLE
Add extra fonts to GeoServer

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/testbed16#18]
add extra fonts in the docker [image build process](https://github.com/geosolutions-it/docker-geoserver/blob/tb16/custom_build.sh)

**Comment by aaime** [comment]
The fonts being the microsoft ones, Arial and company.

**Comment by randomorder** [comment]
@paltaa please go ahead and add the fonts to the docker image

**Comment by paltaa** [comment]
@randomorder ok, working on this

**Comment by randomorder** [comment]
should be in @aaime 
![image](https://user-images.githubusercontent.com/5264230/84489954-c51e5400-aca2-11ea-9b04-57ef2f694929.png)

are we good?
