### ISSUE TITLE
Fix GeoServer PROXY_BASE_URL

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/testbed16#19]
In GeoServer Layer preview we got links like this one:
`https://tb16.geo-solutions.it/geoserver/web/wicket/bookmarkable/$%7BX-Forwarded-Proto%7D://$%7BX-Forwarded-Host%7D/geoserver/oszoom/wms?service=WMS&version=1.1.0&request=GetMap&layers=oszoom%3Azoomstack-outdoor&bbox=-118397.00155160861%2C-15982.135610342928%2C751441.7791101651%2C1272149.3463547546&width=518&height=768&srs=EPSG%3A27700&format=application/openlayers`

Notice the `$%7BX-Forwarded-Proto%7D://$%7BX-Forwarded-Host%7D`

This means the header based proxy base URL was not working properly. I temporary removed it by comenting it out in the compose file [here ](https://github.com/geosolutions-it/testbed16/blob/master/stack/geoserver/geoserver.yml#L48) but need to be investigated ans patched permanently in the repository

**Comment by randomorder** [comment]
please take a look @paltaa

**Comment by paltaa** [comment]
Ok, going to chek this now

**Comment by paltaa** [comment]
Okay, changed the PROXY_BASE_URL variable in the .env, pushed the change @randomorder can you confirm is fixed?

**Comment by randomorder** [comment]
ok, thanks
Next time make a PR instead of a direct push please
