### ISSUE TITLE
Add the "jep" package via pip3 in the TB16 docker image

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/testbed16#20]
The rHealPix DGGS integration with Java needs the [jep library](https://github.com/ninia/jep), which can be installed via pip3.
If memory servers me correctly the installation requires a JAVA_HOME variable defined, as it needs to build some Java classes.

Some info from my local machine:
```
pip3 show jep
Name: jep
Version: 3.9.0
Summary: Jep embeds CPython in Java
Home-page: https://github.com/ninia/jep
Author: Jep Developers
Author-email: jep-project@googlegroups.com
License: zlib/libpng
Location: /home/aaime/.local/lib/python3.8/site-packages
Requires: 
Required-by: 
```

**Comment by randomorder** [comment]
Installed and deployed. Testing
