### ISSUE TITLE
Setup Testbed 16 server

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/testbed16#6]
The server will have to host:

- The secured OS Mastermap Topography dataset (230+GB)
- The OS Zoomstack dataset (12GB)
- The GeoPackage process extension, along with WPS
- The upcoming DGGS server module

Hardware wise we need:

- 4GB RAM minimum (8 would be better)
- 2 cores minimum (4 would be better, but 2 fast CPUs will do the trick too)
- 512GB dedicated disk storage, possibly fast, for the source GeoPackages and PostGIS (plus some extra for the server to dump output GeoPackages, like 30-40GB). 
- SSL encryption support on all connections (best if plain http connections are completely disallowed)

**Comment by aaime** [comment]
@simboss who should I assign this ticket to?
Asked quickly to @allyoucanmap the vtp2 machine could have enough storage, though it's on spinning disks (well it will be slower, not the end of the world I guess).

**Comment by simboss** [comment]
@randomorder by default is the one to bother

**Comment by aaime** [comment]
@randomorder consider yourself bothered :-D

**Comment by aaime** [comment]
I believe roughly 2 years from now. @simboss do we need to keep the servers running for one or two years after the end of the testbed? (which will be in december?)

**Comment by randomorder** [comment]
@aaime 
We bough the new server. Its equipped with SSD storage. We're installing the base system.
I'll keep you posted

**Comment by simboss** [comment]
@randomorder how are we going here?

**Comment by aaime** [comment]
A note here, the TB16 activity does not need any of the layers of VTP2, so the server migration could be avoided. On the other end, if you want to share the two, in order to free up some resources, it's all the same to me.

**Comment by randomorder** [comment]
> @randomorder how are we going here?

no progress

**Comment by aaime** [comment]
Any chance we can have the server up and running... like real soon? Need to show some progress in TB16.

**Comment by paltaa** [comment]
Everything is in repo: https://github.com/geosolutions-it/testbed16

Deployed the servers to: http://tb16.geo-solutions.it/geoserver

It also has prometheus/grafana stack to monitor the containers: http://tb16.geo-solutions.it/grafana

Somone review the deployment is allright as its my first geoserver task

**Comment by Gnafu** [comment]
@paltaa :
- Is there a document with all the credentials you set up on the server?
  - For Linux users
  - For GeoServer
  - For Grafana
- I see GeoServer has the default credentials, please use custom passwords as it is a public facing server.
- If Grafana also has the default passwords, please change them.

@randomorder :
- Were the following lines part of the requirements?
  - The secured OS Mastermap Topography dataset (230+GB)
  - The OS Zoomstack dataset (12GB)
  - The GeoPackage process extension, along with WPS
  - The upcoming DGGS server module
- SSL is not enabled but this was expected as we told Juan that we will take care of that part.
  - we need an issue to keep track of that.
- Is this for C115-2020-OGC-OWS16?

**Comment by aaime** [comment]
I will do the data setup myself (will need credentials for data transfers and the like).
However, these need to be added: "The GeoPackage process extension, along with WPS"

**Comment by paltaa** [comment]
Geosolutions user has no password, its ssh hardened to only use known keys. 
Grafana password is changed, where should all the passwords live, here, a document?

**Comment by Gnafu** [comment]
@paltaa please use this one: https://docs.google.com/document/d/1faQPr3F1Ey3-Vm9qJ6O1IDvl15nq0bPyEDhms6P3-FY/edit#

@aaime I put your public key on the "geosolutions" user : geosolutions@tb16.geo-solutions.it

@aaime @randomorder I see there is some work planned for the geopackage wps process, we should set up a build on our build server that builds GeoServer and creates a docker image to be used on the server.
Am I correct or the deploy was planned differently?

**Comment by paltaa** [comment]
@Gnafu Changed password and updated document

**Comment by Gnafu** [comment]
I created an issue to track the custom docker image build: https://github.com/geosolutions-it/testbed16/issues/14

and an issue to track the TLS support: https://github.com/geosolutions-it/testbed16/issues/15

@paltaa thank you for the password change. Can you please review the readme so we are able to deploy the server from scratch? I noted a few issues at the moment: 
- `run_all.sh` vs `start_all.sh`
- There is a note.txt with the password, is it used? Can I just use a custom password by my choice on new installations?
- In the commit https://github.com/geosolutions-it/testbed16/commit/389a9096aabb91e6957f05dc19ea4e4525f2d805 you remove the override file, that included some environment variables and a network definition, but you didn't include them in the main yml file. Why?

**Comment by simboss** [comment]
@randomorder I turned this into an epic and linked the other issues.

I need this going by the end of the week, if possible.

**Comment by paltaa** [comment]
@Gnafu should i bring back the override file? run_all versus start_all is a typo. Will remove the password from repo

**Comment by Gnafu** [comment]
> @Gnafu should i bring back the override file? 
Yes, It was defining the "slaves" instances, while the main yml only defines a "master" instance.
The master instance is usually accessible only by the administrators, while the slaves handle the load from the end users.

@randomorder was a master-slave configuration planned for TB16? Or should it be a single geoserver instance?

**Comment by randomorder** [comment]
> @randomorder was a master-slave configuration planned for TB16? Or should it be a single geoserver instance?

No cluster, just one instance

**Comment by paltaa** [comment]
@randomorder So, when we are talking about 1 instance is the master or the slave?

**Comment by randomorder** [comment]
Doesn't really matter. The master / slave nouns in this kind of setup is
more of a logical grouping of geoserver instances that are identical in
terms of capabilities.
When we have only one instance there is no distinction between master and
slave.

Right now we have only one instance running, right? Let's just keep it that
way no need to change anything

Il lun 1 giu 2020, 20:22 Juan Pablo Quiroga <notifications@github.com> ha
scritto:

**Comment by randomorder** [comment]
If you want to know more about geoserver clustering we have a nice intro in the [geosolutions training pages](https://geoserver.geo-solutions.it/edu/en/clustering/index.html#clustering-geoserver)

**Comment by paltaa** [comment]
@Gnafu Okay, added the override, using the config for the slave in your example
